EMBEDDING_COLLECTION = "candidate_embeddings"
AGENT_MEMORY_COLLECTION = "agent_memory"

INTERVIEW_STATUS_PENDING = "pending"
INTERVIEW_STATUS_COMPLETED = "completed"

EVALUATION_STATUS_PENDING = "pending"
EVALUATION_STATUS_COMPLETED = "completed"